name: new
services:
  lighthouse-exporter:
    image: lighthouse-exporter-yobushka
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lighthouse-exporter
    networks:
      default: null
    ports:
    - mode: ingress
      target: 9593
      published: "9593"
      protocol: tcp
    restart: always